# Generated by Django 2.0.2 on 2023-05-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apiinfo',
            fields=[
                ('createTime', models.DateTimeField(auto_now=True)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ApiId', models.CharField(max_length=255, verbose_name='接口英文名')),
                ('ApiName', models.CharField(max_length=255, verbose_name='接口中文名')),
                ('Url', models.URLField()),
                ('Type', models.CharField(max_length=255, verbose_name='接口类型，GET，POST，UPDATE等')),
                ('Headers', models.TextField(verbose_name="'请求头，里面放json串")),
                ('Auth', models.TextField(blank=True, verbose_name="'是否鉴权，只做标识作用")),
            ],
            options={
                'verbose_name': '接口详情',
                'verbose_name_plural': '接口详情',
                'db_table': 'apiInfo',
            },
        ),
        migrations.CreateModel(
            name='SqlCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('0', '后置校验'), ('1', '后置校验')], default=None, max_length=255)),
                ('sql_id', models.IntegerField(default=None, null=True)),
                ('case_id', models.IntegerField(default=None, null=True)),
                ('sql', models.CharField(default=None, max_length=255, null=True)),
                ('expected', models.CharField(default=None, max_length=255, null=True)),
                ('actual', models.CharField(default=None, max_length=255, null=True)),
                ('check_result', models.CharField(choices=[('1', '校验失败'), ('0', '校验通过')], default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'sql校验',
                'verbose_name_plural': 'sql校验',
                'db_table': 'sqlCheck',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('createTime', models.DateTimeField(auto_now=True)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseId', models.CharField(db_index=True, max_length=255, unique=True)),
                ('caseRemark', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ApiId', models.CharField(db_index=True, max_length=255, unique=True)),
                ('requestData', models.TextField()),
                ('expectedStatusCode', models.TextField(verbose_name='期望的状态码')),
                ('extractRespData', models.TextField()),
                ('expectedRespKeyInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('checkType', models.CharField(choices=[('0', '校验成功'), ('1', '校验失败')], default=None, max_length=255)),
            ],
            options={
                'verbose_name': '接口case详情',
                'verbose_name_plural': '接口case详情',
                'db_table': 'testCaseInfo',
            },
        ),
    ]
