# Generated by Django 4.1.7 on 2023-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filecreate_at',
            field=models.DateTimeField(default=None, verbose_name='文件生成时间'),
        ),
    ]
