# Generated by Django 4.1.7 on 2023-05-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportData', '0002_alter_datafile_filecreate_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqllist',
            name='sqlquery',
            field=models.TextField(verbose_name='SQL语句'),
        ),
    ]
