# Generated by Django 4.1.7 on 2023-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportData', '0003_alter_sqllist_sqlquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(max_length=1280, upload_to='exportdata/', verbose_name='文件'),
        ),
    ]
