# Generated by Django 4.1.7 on 2023-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportData', '0004_alter_datafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
