# Generated by Django 4.1.7 on 2023-05-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportData', '0005_sqllist_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqllist',
            name='deleted_at',
        ),
    ]
